#ifndef _EDGE_DEFINES_H_
#define  _EDGE_DEFINES_H_

#define OCALL_PRINT_BUFFER 1
#define OCALL_PRINT_VALUE 2
#define OCALL_SEND_REPORT 3
#define OCALL_WAIT_FOR_MESSAGE 4
#define OCALL_SEND_REPLY 5
#define OCALL_WAIT_FOR_CLIENT_PUBKEY 6
#define OCALL_SEND_SERVER_PUBKEY 7
#define OCALL_GET_REPORT_SIZE 8

#endif /* _EDGE_DEFINES_H_ */
